#!/bin/bash
#set -x

# Restore original (uncompressed) JavaScript files

FILES=`find . -name '*.js-orig' -type f |grep -v '^\./vendor/' |grep -v richtexteditor`
for file in $FILES; do
	ofile=${file::-5}
	mv $file $ofile
	echo $file " -> " $ofile
done

